#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
    echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Example usage
# In this example it's used to run `npm install` if package.json changed
check_run testfile "touch newfile"
check_run testfile1 "touch newfile1"
check_run testfile2 "touch newfile2"
check_run testfile3 "touch newfile3"
check_run testfile4 "touch newfile4"

check_run symlinktest1 "touch symlinknew1"
check_run symlinktest2 "touch symlinknew2"
